Praktikmoede/Models/ErrorViewModel.cs
using System;

namespace Praktikmoede.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Praktikmoede/Models/Moede.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Praktikmoede.Models
{
    public class Moede
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public int dateFrom { get; set; }

        [Required]
        public string topic { get; set; }   


    }
}

Praktikmoede/Models/MoedeDeltager.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Praktikmoede.Models
{
    public class MoedeDeltager
    {
        [Key]
        public int Id { get; set; }
        public string Initials { get; set; }
        public string Name { get; set; }
        [Required]
        [DisplayName("Moede")]
        public int MoedeId { get; set; }

        [ForeignKey("MoedeId")]
        public virtual Moede Moede { get; set; }

    }
}

Praktikmoede/ViewModels/MoedeDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Praktikmoede.Models;

namespace Praktikmoede.ViewModels
{
    public class MoedeDetails
    {
        public Moede moede { get; set; }
        public List<MoedeDeltager> moedeDeltagere { get; set; }
    }
}

Praktikmoede/Areas/Customer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Praktikmoede.Models;

namespace Praktikmoede.Controllers
{
        [Area("Customer")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Praktikmoede/Areas/Customer/Controllers/MoedeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Praktikmoede.Data;
using Praktikmoede.Models;
using Praktikmoede.ViewModels;

namespace Praktikmoede.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class MoedeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MoedeController(ApplicationDbContext db)
        {
            _db = db;
        }

        //GET
        public async Task<IActionResult> Index()
        {
            return View(await _db.Moede.ToListAsync());
        }
        //GET Create
        public IActionResult Create()
        {
            return View();
        }

        //Get Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var moede = await _db.Moede.FindAsync(id);
            if(moede==null)
            {
                return NotFound();
            }
            return View(moede);
        }
        //Get Details
        public async Task<IActionResult> Details(int? id)
        {

            MoedeDetails moedeDetails = new MoedeDetails();
            moedeDetails.moede = await _db.Moede.FindAsync(id);
            moedeDetails.moedeDeltagere = await _db.MoedeDeltager.Include(s => s.Moede).Where(s => s.MoedeId == id).ToListAsync();
            return View(moedeDetails);


        }

        //POST
        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> Create(Moede moede)
        {
            if(ModelState.IsValid)
            {
                _db.Moede.Add(moede);
                await _db.SaveChangesAsync() ;

                return RedirectToAction(nameof(Index));
            }
            return View(moede);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var moede = await _db.Moede.FindAsync(id);
            _db.Moede.Remove(moede);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //GET - Edit

        public async Task<IActionResult> Edit(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var moede = await _db.Moede.FindAsync(id);
            if(moede==null)
            {
                return NotFound();
            }
            return View(moede); 
        }

        //POST -Edit
        [HttpPost]
        public async Task<IActionResult> Edit(Moede moede)
        {
            if (ModelState.IsValid)
            {
                _db.Update(moede);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            return View(moede);
        }
    }
}

Praktikmoede/Areas/Customer/Controllers/MoedeDeltagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Praktikmoede.Data;
using Praktikmoede.Models;

namespace Praktikmoede.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class MoedeDeltagerController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MoedeDeltagerController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var MoedeDeltagere = await _db.MoedeDeltager.Include(s => s.Moede).ToListAsync();
            return View(MoedeDeltagere);
        }
    }
}

Praktikmoede/Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Praktikmoede/Areas/Customer/Views/Moede/Create.cshtml
@model Moede
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-info">Create Moede</h2>

<br />
<form method="post" asp-action="Create">
<div class="border backgroundWhite">
    <div asp-validation-summary="ModelOnly" class="text-danger" />
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="topic" class="col-form-label"></label>
        </div>
        <div class="col-5">
            <input asp-for="topic" class="form-control" />
        </div>
        <span asp-validation-for="topic" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="dateFrom" class="col-form-label"></label>
        </div>
        <div class="col-5">
            <input asp-for="dateFrom" class="form-control" />
        </div>
        <span asp-validation-for="dateFrom" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <div class="col-5 offset-2">
           <partial name="_CreateButtonPartial"/>
        </div>
    </div>
</div>
    </form>
<br />

Praktikmoede/Areas/Customer/Views/Moede/Delete.cshtml
@model Praktikmoede.Models.Moede 
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 class="text-info">Delete Møde</h2>

<br />
<form method="post" asp-action="Delete">
    <div class="border backgroundWhite">
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="dateFrom" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="dateFrom" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Id" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Id" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-5 offset-2">
                <div class="row">
                    <div class="col-6">
                        <input type="submit" class="btn btn-danger form-control" asp-route-Id="@Model.Id" value="Delete" />
                    </div>
                    <div class="col-6">
                        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</form>

Praktikmoede/Areas/Customer/Views/Moede/Details.cshtml
@model Praktikmoede.ViewModels.MoedeDetails
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>
<br />
<div>Titel: @Model.moede.topic.ToString()</div>
<br />
<div>Dato: @Model.moede.dateFrom.ToString()</div>
<br />
<div class="row">
    <div class="col-6">Deltagerliste</div>
    <div class="col-6">
        <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp; Create New</a>
    </div>
    <br />
    <div class="col-6">
        <table class="table-striped boarder">
            <tr>
                <th>Møde</th>
                <th>Initialer</th>
                <th>Navn</th>
            </tr>
            @foreach (var deltager in Model.moedeDeltagere)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m => deltager.Moede.topic)
                    </td>
                    <td>
                        @Html.DisplayFor(m => deltager.Initials)
                    </td>
                    <td>
                        @Html.DisplayFor(m => deltager.Name)
                    </td>
                    <td>
                        <partial name="_TableButtonPartial" model="deltager.Id" />
                    </td>
                </tr>
            }
        </table>
    </div>
</div>
</div>

Praktikmoede/Areas/Customer/Views/Moede/Edit.cshtml
@model Praktikmoede.Models.Moede

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<br />
<form method="post" asp-action="Create">
    <div class="border backgroundWhite">
        <div asp-validation-summary="ModelOnly" class="text-danger" />
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="topic" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="topic" class="form-control" />
            </div>
            <span asp-validation-for="topic" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="dateFrom" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="dateFrom" class="form-control" />
            </div>
            <span asp-validation-for="dateFrom" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-5 offset-2">
                <div class="row">
                    <div class="col-6">
                        <input type="submit" class="btn btn-info form-control" asp-route-id="@Model.Id" value="Update"/>
                    </div>
                    <div class="col-6">
                        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<br />

Praktikmoede/Areas/Customer/Views/Moede/Index.cshtml
@model IEnumerable<Moede>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
<br/>
<div>
    <div class="row">
        <div class="col-6">Møde Liste</div>
        <div class="col-6">
            <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp; Create New</a>
        </div>
        <br/>
        <div class="col-6">
            <table class="table-striped boarder">
            <tr>
                <th>Dato</th>
                <th>Emne</th>
            </tr>
            @foreach(var moede in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(m => moede.dateFrom)
                </td>
                <td>
                    @Html.DisplayFor(m => moede.topic)
                </td>
                <td>
                    <partial name="_TableButtonPartial" model="moede.Id"/>
                </td>
            </tr>

            }
            </table>
        </div>
    </div>
</div>

Praktikmoede/Areas/Customer/Views/MoedeDeltager/Index.cshtml
@model IEnumerable<MoedeDeltager>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
<br />
<div>
    <div class="row">
        <div class="col-6">Deltagerliste</div>
        <div class="col-6">
            <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp; Create New</a>
        </div>
        <br />
        <div class="col-6">
            <table class="table-striped boarder">
                <tr>
                    <th>Møde</th>
                    <th>Initialer</th>
                    <th>Navn</th>
                </tr>
                @foreach (var deltager in Model)
                {
            <tr>
                <td>
                    @Html.DisplayFor(m => deltager.Moede.topic)
                </td>
                <td>
                    @Html.DisplayFor(m => deltager.Initials)
                </td>
                <td>
                    @Html.DisplayFor(m => deltager.Name)
                </td>
                <td>
                    <partial name="_TableButtonPartial" model="deltager.Id" />
                </td>
            </tr>

                }
            </table>
        </div>
    </div>
</div>

Praktikmoede/Views/Shared/_CreateButtonPartial.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-6">
        <a asp-action="Index" asp-controller="Moede" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Praktikmoede/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Praktikmoede</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/b86c74e545.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Praktikmoede</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Moede" asp-action="Index">Møde</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="MoedeDeltager" asp-action="Index">Deltagere</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Praktikmoede - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Praktikmoede/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>
        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>
        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@